# Ch_18
## 예외 처리 (Exception Handling)
* 논리적 오류를 처리 
* 예외 클래스는 Throwable의 하위 클래스인 Exception 클래스를 상속해서 정의
* 예외상황이 메소드 내에서 처리되지 않으면, 메소드를 호출한 영역으로 예외의 처리가 넘어감
* throw는 예외 인스턴스의 참조변수를 기반으로 구성
* 예외가 발생은 되었는데 처리하지 않으면 계속해서 반환이 되어 main 메소드를 호출한 가상머신에게 전달
* 호출하고자 하는 메소드가 예외를 발생시킬 수 있다면, try~catch문 또는 throws 두 가지 중 한가지 조치를 취해야 한다 (API 문서의 참조가 필요)

### if 문 예외 처리
* if 문이 프로그램의 주요 흐름인지, 예외 처리인지 구분이 되지 않는 단점이 있다

### try ~ catch 문
* try - 예외발생이 예상되는 지역을 표현하는 목적으로 사용
* catch - 발생한 예외상황의 처리를 위한 목적으로 사용
* try 문 내에서 예외상황이 발생하고 처리된 다음에는, 나머지 try문을 건너뛰고, try~catch의 이후에 실행한다는 특징으로 인해 트랜잭션(transaction)의 구성이 용이
* 하나의 try 블록에 둘 이상의 catch 블록을 구성할 수 있다, 따라서 예외처리와 관련된 부분을 별도로 떼어 놓을 수 있다
* catch가 결정되는 방법 -> 첫 번째 catch 블록에서부터 순서대로, catch 블록의 매개변수가 해당 예외 인스턴스의 참조 값을 받을 수 있는지 확인하면서 내려온다

### getMessage()
* ArithmaticException 클래스와 같이 예외상황을 알리기 위해 정의된 클래스
* 모든 예외 클래스는 Throwable 클래스를 상속, 이 클래스에는 getMessage 메소드가 정의
* getMessage 메소드는 예외가 발생한 원인정보를 문자열의 형태로 반환

### finally
* finally와 연결되어 있는 try 블록으로 일단 진입을 하면 무조건 실행되는 영역, 중간에 return 문을 실행하더라도, finally 블록이 실행된 다음에 메소드를 빠져 나간다

### 처리하지 않아도 되는 RuntimeException
* Exception 클래스의 하위 클래스
* Error를 상속하는 예외 클래스만큼 치명적인 예외상황의 표현에 사용되지 않는다
* ArrayIndexOutOfBoundsException -> 배열의 접근에 잘못된 인덱스 값을 사용하는 예외상황
* ClassCastException -> 허용할 수 없는 형변환 연산을 진행하는 예외상황
* NegativeArraySizeException -> 배열선언 과정에서 배열의 크기를 음수로 지정하는 예외상황
* NullPointerException -> 참조변수가 null로 초기화 된 상황에서 메소드를 호출하는 예외상황
